### ISSUE TITLE
Download doesn't work if there is a space in the wget path.

### ISSUE THREAD

**Issue by radosuav** [DHI-GRAS/sentinel_download#3]
E.g. C:\Users\user name\\.qgis2\processing\scripts\sentinel_download\bundle\wget_provider\wget_provider\windows_binaries\wget64.ext

Can be fixed by changing line 40 of provide.py to:
```
wget_cmd = '"'+os.path.join(windows_binaries, wget_exe)+'"'
```

**Comment by j08lue** [comment]
Thanks for reporting this. I fixed it in `wget_provider` but will soon replace this `sentinel_download` by the new [sentinelsat](https://github.com/sentinelsat/sentinelsat), which now relies only on `requests` for downloading and will be easy to integrate with QGIS.
